version: '3.8'

services:
  tork_crm_app:
    container_name: tork_crm_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:3000"
    environment:
      - DATABASE_URL=postgresql://tork_user:tork_pass@tork_crm_db:5432/tork_crm?schema=public
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - tork_crm_db
    networks:
      - tork_network
      - app_network

  tork_crm_db:
    container_name: tork_crm_db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: tork_user
      POSTGRES_PASSWORD: tork_pass
      POSTGRES_DB: tork_crm
    volumes:
      - tork_pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Mantendo 5433 para n√£o conflitar com banco do Chatwoot (5432)
    networks:
      - tork_network
      - app_network

networks:
  tork_network:
    driver: bridge
  app_network:
    external: true

volumes:
  tork_pg_data:
